apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socializer-backend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: backend.socializer.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: socializer-backend
                port:
                  number: 80
  tls:
    - hosts:
        - backend.socializer.example.com
      secretName: socializer-backend-tls
